"""Compile workspace subagent descriptors into each engine's native format.

A single descriptor (``.archon-horizon/subagents/<name>.md`` or a bundled
default) is the source of truth. At run start we render every enabled descriptor
into the workspace-local native config the active engine discovers on its own:

  - Claude Code → ``<workspace>/.claude/agents/<name>.md``
  - Codex       → ``<workspace>/.codex/agents/<name>.toml``

Dispatch (parallelism, approvals, model, and effort) then belongs to the Horizon
agent through the engine's native mechanism; Horizon only installs the role
descriptors. Generated descriptors deliberately omit model settings, so helpers
inherit unless the Horizon agent chooses a different model for that particular
dispatch. ``read_only`` maps to each engine's own enforcement
(Claude ``disallowedTools``; Codex ``sandbox_mode = "read-only"``) — a real,
engine-enforced guarantee rather than a prompt-only request.

Writes are non-destructive: we only ever (over)write files that carry our
generated-marker, so a hand-authored native agent sharing a name is left alone.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from pathlib import Path

from archon_horizon.config.schema import HarnessConfig

from .base import SubagentDescriptor
from .registry import load_descriptors

# Tools an engine must deny to make a subagent read-only on source files.
_READ_ONLY_DENY = ("Edit", "Write", "NotebookEdit")

_MARKER = "Generated by Archon Horizon"


def _marker_line(name: str, comment: str) -> str:
    """A leading comment (``#`` works for both YAML frontmatter and TOML)."""
    return (
        f"{comment} {_MARKER} from .archon-horizon/subagents/{name}.md "
        f"— edits are overwritten on the next run."
    )


def _toml_basic(value: str) -> str:
    """A single-line TOML basic string with the escapes TOML requires."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def render_claude_agent(descriptor: SubagentDescriptor, harness: HarnessConfig) -> str:
    """A ``.claude/agents/<name>.md`` file: YAML frontmatter + system prompt body."""
    lines = ["---", _marker_line(descriptor.name, "#"), f"name: {descriptor.name}"]
    # Description is a YAML flow scalar; quote to stay safe with ``\`` and ``:``.
    desc = descriptor.description.strip().replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'description: "{desc}"')
    if descriptor.read_only:
        lines.append("disallowedTools: [" + ", ".join(_READ_ONLY_DENY) + "]")
    lines.append("---")
    body = descriptor.prompt_body.strip()
    return "\n".join(lines) + "\n\n" + body + "\n"


def render_codex_agent(
    descriptor: SubagentDescriptor, harness: HarnessConfig, skills_appendix: str = ""
) -> str:
    """A ``.codex/agents/<name>.toml`` standalone custom-agent file.

    ``skills_appendix`` is inlined into the instructions so Codex subagents learn
    the workspace skills — Codex has no ``.claude/skills`` auto-discovery, so
    unlike Claude they must be told the skills exist and where to read them."""
    lines = [_marker_line(descriptor.name, "#")]
    lines.append(f"name = {_toml_basic(descriptor.name)}")
    lines.append(f"description = {_toml_basic(descriptor.description.strip())}")
    if descriptor.read_only:
        lines.append('sandbox_mode = "read-only"')
    # ``developer_instructions`` carries the prompt body. Use a multiline LITERAL
    # string ('''...''') so the LaTeX backslashes in our prompts (\uses, \lean, …)
    # are not interpreted as TOML escapes.
    body = descriptor.prompt_body.strip()
    if skills_appendix:
        body = f"{body}\n\n{skills_appendix.strip()}"
    body = body.replace("'''", "''")
    lines.append("developer_instructions = '''\n" + body + "\n'''")
    return "\n".join(lines) + "\n"


def _write_if_ours(path: Path, content: str) -> bool:
    """Write ``content`` unless ``path`` exists and was NOT generated by us.

    Returns True if written. A hand-authored file (no marker) is preserved.
    """
    if path.exists():
        try:
            if _MARKER not in path.read_text("utf-8"):
                return False
        except OSError:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, "utf-8")
    return True


def _enabled(descriptors: Iterable[SubagentDescriptor]) -> list[SubagentDescriptor]:
    return [d for d in descriptors if d.default_enabled]


def _prune_ours(dest_dir: Path, keep: Iterable[str], suffix: str) -> None:
    """Delete our previously-generated native agents that are no longer in the
    roster, so a removed/renamed descriptor doesn't leave a stale agent the
    engine still discovers. Only touches files carrying our marker; a
    hand-authored native agent (no marker) is never deleted."""
    if not dest_dir.is_dir():
        return
    keep_set = set(keep)
    for path in dest_dir.glob(f"*{suffix}"):
        if path.stem in keep_set:
            continue
        try:
            if _MARKER in path.read_text("utf-8"):
                path.unlink()
        except OSError:
            continue


def compile_for_claude(
    descriptors: Iterable[SubagentDescriptor], harness: HarnessConfig, dest_dir: Path
) -> list[str]:
    written: list[str] = []
    for d in _enabled(descriptors):
        if _write_if_ours(dest_dir / f"{d.name}.md", render_claude_agent(d, harness)):
            written.append(d.name)
    _prune_ours(dest_dir, {d.name for d in _enabled(descriptors)}, ".md")
    return written


def compile_for_codex(
    descriptors: Iterable[SubagentDescriptor], harness: HarnessConfig, dest_dir: Path,
    skills_appendix: str = "",
) -> list[str]:
    written: list[str] = []
    for d in _enabled(descriptors):
        if _write_if_ours(dest_dir / f"{d.name}.toml", render_codex_agent(d, harness, skills_appendix)):
            written.append(d.name)
    _prune_ours(dest_dir, {d.name for d in _enabled(descriptors)}, ".toml")
    return written


def _codex_skills_appendix(workspace_root: Path) -> str:
    """A compact skills index for Codex agents: names + descriptions + the
    absolute ``SKILL.md`` paths to read on demand. Absolute so it resolves no
    matter which project directory the codex session runs in. Empty if no skills."""
    from archon_horizon.skills.registry import available_skills

    skills = available_skills()
    if not skills:
        return ""
    skills_dir = (workspace_root / ".claude" / "skills").resolve()
    skill_lines: list[str] = []
    for skill in skills:
        line = f"- {skill.name} — {skill.description} (read `{skills_dir / skill.name / 'SKILL.md'}`)"
        if skill.recommendation:
            line += f"\n  Advisory recommendation (optional): {skill.recommendation}"
        skill_lines.append(line)
    lines = "\n".join(skill_lines)
    return (
        "# Skills\n"
        "Capability know-how lives in skill files. Before acting, read the relevant "
        "SKILL.md (exact inbox verbs, lean checks, blueprint conventions, the dependency DAG). "
        "Invoke the Horizon CLI via the `$HORIZON_BIN` env var (an absolute path); most "
        "`horizon` commands accept `--json`.\n"
        f"{lines}"
    )


def _first_of_kind(harnesses: Mapping[str, HarnessConfig], kind: str) -> HarnessConfig | None:
    for cfg in harnesses.values():
        if cfg.kind == kind:
            return cfg
    return None


def install_subagents(
    workspace_root: Path,
    descriptor_dir: Path,
    harnesses: Mapping[str, HarnessConfig],
) -> dict[str, list[str]]:
    """Compile descriptors into native agents for every engine in use.

    Emits Claude and/or Codex native subagents (workspace-local) depending on
    which engine kinds appear in ``harnesses``. The generated native descriptors
    omit model and effort so the parent Horizon agent controls each dispatch.
    Returns ``{engine: [names written]}``.
    """
    descriptors = load_descriptors(_builtin_dir())
    descriptors.update(load_descriptors(descriptor_dir))
    roster = list(descriptors.values())

    out: dict[str, list[str]] = {}
    claude_cfg = _first_of_kind(harnesses, "claude-code")
    if claude_cfg is not None:
        out["claude"] = compile_for_claude(roster, claude_cfg, workspace_root / ".claude" / "agents")
    codex_cfg = _first_of_kind(harnesses, "codex")
    if codex_cfg is not None:
        # Codex has no `.claude/skills` auto-discovery, so inline a skills index
        # into each codex agent (Claude discovers the same skills on its own).
        appendix = _codex_skills_appendix(workspace_root)
        out["codex"] = compile_for_codex(
            roster, codex_cfg, workspace_root / ".codex" / "agents", appendix
        )
    return out


def _builtin_dir() -> Path:
    return Path(__file__).parent / "descriptors"
