"""Generate the harness MCP config (``.mcp.json``) for Lean tooling.

Claude Code reads ``.mcp.json`` from the working directory and surfaces the
declared MCP servers to the agent. We register the Lean language-server MCP so
the Horizon agent gets live diagnostics / hover / go-to-definition instead of
shelling ``lake build`` repeatedly. The server binary itself is external
(installed by ``setup``); here we only declare how to launch it. Merging is
non-destructive so hand-added servers survive a re-init.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

from .schema import HarnessConfig

# Launched via uvx so no global install is required; setup verifies availability.
LEAN_LSP_SERVER: dict[str, Any] = {"command": "uvx", "args": ["lean-lsp-mcp"]}

# Our own offline declaration search (mathlib + configured external_libraries).
# Runs from the bundled package via the current interpreter — no extra install,
# no GPU/API key. cwd is the workspace root (where Claude Code launches it).
LEANSEARCH_SERVER: dict[str, Any] = {
    "command": sys.executable,
    "args": ["-m", "archon_horizon.search.mcp_server"],
}

_LEANSEARCH_MODULE_ARGS = ["-m", "archon_horizon.search.mcp_server"]


def _is_managed_leansearch(name: str, spec: Any) -> bool:
    """Whether ``spec`` is the leansearch entry generated by Horizon.

    The interpreter path is intentionally not part of the signature: that is
    the machine-local value that must be refreshed after an installation or
    workspace moves.  A user-defined server that happens to use the same name
    but different arguments remains untouched.
    """
    return (
        name == "leansearch"
        and isinstance(spec, dict)
        and spec.get("args") == _LEANSEARCH_MODULE_ARGS
    )


def default_mcp_servers() -> dict[str, dict[str, Any]]:
    return {"lean-lsp": dict(LEAN_LSP_SERVER), "leansearch": dict(LEANSEARCH_SERVER)}


def merge_mcp_config(existing: dict[str, Any], servers: dict[str, dict[str, Any]]) -> dict[str, Any]:
    """Add ``servers`` and refresh stale Horizon-managed entries.

    Hand-added servers are never clobbered.  Horizon's leansearch entry is
    refreshed because its absolute interpreter path is machine-local and may
    become stale when the installation or workspace is moved.
    """
    out = dict(existing)
    merged = dict(out.get("mcpServers", {}))
    for name, cfg in servers.items():
        current = merged.get(name)
        if current is None or (
            _is_managed_leansearch(name, current)
            and _is_managed_leansearch(name, cfg)
        ):
            merged[name] = cfg
    out["mcpServers"] = merged
    return out


def write_mcp_config(path: Path, servers: dict[str, dict[str, Any]] | None = None) -> list[str]:
    """Merge the given (or default) servers into ``path``; return server names."""
    servers = default_mcp_servers() if servers is None else servers
    existing: dict[str, Any] = {}
    if path.exists():
        try:
            existing = json.loads(path.read_text("utf-8")) or {}
        except json.JSONDecodeError:
            existing = {}
    merged = merge_mcp_config(existing, servers)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(merged, indent=2) + "\n", "utf-8")
    return sorted(merged["mcpServers"])


# ── per-engine MCP registration (so the same servers reach every harness) ──
#
# There is no universal MCP-registration file across engines, so we keep ONE
# canonical server list (``default_mcp_servers``) and write it into each engine's
# own location. Both are workspace-local — only auth lives in the config home:
#   - Claude Code → project ``.mcp.json`` (written at the workspace root)
#   - Codex       → ``[mcp_servers.*]`` in the workspace ``.codex/config.toml``


def _toml_str(value: str) -> str:
    """Minimal TOML basic-string escaping for our known-simple values."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def codex_mcp_toml_block(name: str, spec: dict[str, Any]) -> str:
    """The ``[mcp_servers.<name>]`` TOML block for one stdio server. Pure (testable)."""
    args = ", ".join(_toml_str(str(a)) for a in spec.get("args", []))
    return (
        f"[mcp_servers.{name}]\n"
        f"command = {_toml_str(str(spec['command']))}\n"
        f"args = [{args}]\n"
    )


def _existing_codex_servers(path: Path) -> dict[str, Any]:
    """Servers declared under ``[mcp_servers]`` in a Codex ``config.toml``."""
    if not path.exists():
        return {}
    try:
        import tomllib

        data = tomllib.loads(path.read_text("utf-8"))
    except (OSError, ValueError):
        return {}
    servers = data.get("mcp_servers")
    return dict(servers) if isinstance(servers, dict) else {}


def _refresh_codex_server_command(text: str, name: str, command: str) -> str:
    """Replace one server table's command while preserving the TOML verbatim."""
    header = re.search(
        rf"(?m)^\[mcp_servers\.{re.escape(name)}\][ \t]*(?:\n|$)", text
    )
    if header is None:
        return text
    next_table = re.search(r"(?m)^\[", text[header.end() :])
    end = header.end() + next_table.start() if next_table is not None else len(text)
    block = text[header.start() : end]
    refreshed, count = re.subn(
        r"(?m)^([ \t]*command[ \t]*=[ \t]*).*$",
        lambda match: match.group(1) + _toml_str(command),
        block,
        count=1,
    )
    if count == 0:
        return text
    return text[: header.start()] + refreshed + text[end:]


def write_codex_mcp_config(
    codex_dir: Path, servers: dict[str, dict[str, Any]] | None = None
) -> list[str]:
    """Append our servers to the workspace ``<codex_dir>/config.toml`` (non-destructive).

    Missing ``[mcp_servers.<name>]`` blocks are appended.  Existing
    Horizon-managed leansearch blocks have their machine-local interpreter path
    refreshed; hand-added servers and every other config table are preserved
    verbatim.  Returns the names newly added or refreshed.
    """
    servers = default_mcp_servers() if servers is None else servers
    path = codex_dir / "config.toml"
    present = _existing_codex_servers(path)
    existing = path.read_text("utf-8") if path.exists() else ""
    blocks: list[str] = []
    changed: list[str] = []
    for name, spec in servers.items():
        current = present.get(name)
        if current is not None:
            if (
                _is_managed_leansearch(name, current)
                and _is_managed_leansearch(name, spec)
            ):
                refreshed = _refresh_codex_server_command(
                    existing, name, str(spec["command"])
                )
                if refreshed != existing:
                    existing = refreshed
                    changed.append(name)
            continue
        blocks.append(codex_mcp_toml_block(name, spec))
        changed.append(name)
    if blocks:
        path.parent.mkdir(parents=True, exist_ok=True)
        sep = existing.rstrip() + "\n\n" if existing.strip() else ""
        existing = sep + "\n".join(blocks)
    if changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(existing, "utf-8")
    return changed


def install_mcp_for_harnesses(
    harness_configs: dict[str, HarnessConfig],
    workspace_root: Path,
    servers: dict[str, dict[str, Any]] | None = None,
) -> dict[str, list[str]]:
    """Register the canonical servers with every non-Claude harness in the config.

    Claude reads the project ``.mcp.json`` (written separately at the workspace
    root), so it isn't handled here. Codex gets the servers in the workspace
    ``.codex/config.toml``. Returns a map of a human label → server names added
    or refreshed.
    """
    servers = default_mcp_servers() if servers is None else servers
    out: dict[str, list[str]] = {}
    if any(cfg.kind == "codex" for cfg in harness_configs.values()):
        out["codex"] = write_codex_mcp_config(workspace_root / ".codex", servers)
    return out
